language: python
install:
  - pip install tox
  - pip install bandit
  - pip install coveralls
script:
  - tox
env:
  - TOXENV=pep8
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=bandit
after_success:
  - coveralls

