name: tox

on:
    push:
        branches: [ master ]
    pull_request:

jobs:
    tox-test:
        strategy:
            matrix:
                os: [ubuntu-latest]
                python:
                    - {version: '3.8', env: py38}
                    - {version: '3.9', env: py39}
                    - {version: '3.10', env: py310}
                    - {version: '3.11', env: py311}
                test_mode: [0, 1]
        runs-on: ${{ matrix.os }}
        env:
            TOXENV: ${{ matrix.python.env }}
            RUN_INTEGRATION_TESTS: ${{ matrix.test_mode }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python.version }}
            - run: pip install tox
            - run: pip install codecov
            - run: pip install slugs
            - run: python3 setup.py install
            - run: ./.travis/run.sh
            - run: codecov
    tox-other:
        strategy:
            matrix:
                os: [ubuntu-latest]
                python: ['3.8', '3.9', '3.10', '3.11']
                test: [pep8, bandit, docs]
        runs-on: ${{ matrix.os }}
        env:
            TOXENV: ${{ matrix.test }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python }}
            - run: pip install tox
            - run: pip install bandit
              if: ${{ matrix.test == 'bandit' }}
            - run: tox
